### ISSUE TITLE
复现时一些报错问题

### ISSUE THREAD

**Issue by so-wee** [HaojunYu1998/UltraDet#2]
我的指令是：
![image](https://github.com/HaojunYu1998/UltraDet/assets/54896658/43329d02-336b-4383-b6e6-d63f3d42f6ef)
报错问题：
![image](https://github.com/HaojunYu1998/UltraDet/assets/54896658/be92465c-fa46-4057-b34d-1b50bf78d6ce)

**Comment by xjtulyc** [comment]
您好，这应该是torch或者detectron2版本和cuda版本不匹配导致的。您可以按照您的CUDA版本，torch官网和detectron2官网的安装方式，重装一下看看。

Hello, this should be caused by a mismatch between the torch or detectron2 version and the cuda version. You can reinstall it according to your CUDA version, torch official website and detectron2 official website to see.
